import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';

const args = parseArgs(process.argv.slice(2));
const count = Number(args.count ?? 1000);
const reviewMax = Number(args.reviewMax ?? 6);
const centerLat = Number(args.lat ?? 37.5657);
const centerLng = Number(args.lng ?? 126.977);
const radiusKm = Number(args.radiusKm ?? 1.7);
const seed = Number(args.seed ?? 20260429);
const prefix = 'demo_cityhall';

let random = seededRandom(seed);

const users = [
  {
    id: stableUuid(`${prefix}:user`),
    nickname: '데모 유저',
  },
];

const places = [];
const toilets = [];
const reviews = [];

for (let index = 0; index < count; index += 1) {
  const point = randomPoint(centerLat, centerLng, radiusKm);
  const signature = `${prefix}:${index + 1}`;
  const placeId = stableUuid(`place:${signature}`);
  const toiletId = stableUuid(`toilet:${signature}`);
  const district = sample(['태평로', '서소문동', '정동', '무교동', '다동', '북창동', '남대문로', '명동']);
  const placeType = sample(['공중화장실', '개방화장실', '역사 화장실', '공원 화장실', '건물 개방화장실']);
  const type = placeType.includes('건물') ? '매장' : '공공';
  const accessType = sample(['누구나', '누구나', '누구나', '손님만', '비밀번호']);
  const genderType = sample(['남녀분리', '남녀분리', '남녀분리', '공용']);
  const floor = sample(['1층', '지하 1층', '2층', '로비층', '외부', null]);
  const name = `시청역 데모 ${placeType} ${String(index + 1).padStart(4, '0')}`;
  const address = `서울특별시 중구 ${district} 데모로 ${index + 1}`;
  const reviewCount = Math.floor(random() * (reviewMax + 1));

  places.push({
    id: placeId,
    name,
    address,
    lat: round(point.lat, 7),
    lng: round(point.lng, 7),
    source: 'user',
    kakao_place_id: `${prefix}:${String(index + 1).padStart(4, '0')}`,
  });

  toilets.push({
    id: toiletId,
    place_id: placeId,
    type,
    access_type: accessType,
    floor,
    gender_type: genderType,
    registered_by: users[0].id,
  });

  for (let reviewIndex = 0; reviewIndex < reviewCount; reviewIndex += 1) {
    const rating = round(3.1 + random() * 1.9, 1);
    reviews.push({
      id: stableUuid(`review:${signature}:${reviewIndex}`),
      toilet_id: toiletId,
      user_id: users[0].id,
      rating,
      cleanliness: rating >= 3.7 || random() > 0.45,
      paper: random() > 0.22,
      soap: random() > 0.3,
      security: rating >= 3.8 || random() > 0.38,
      comment: sample([
        '데모 리뷰입니다. 실제 데이터 import 후 삭제 예정입니다.',
        '시청역 주변 테스트용 리뷰입니다.',
        '지도 성능 확인용 더미 리뷰입니다.',
        null,
      ]),
      is_verified: random() > 0.24,
    });
  }
}

await mkdir('tmp', { recursive: true });
await writeFile(
  'tmp/cityhall-demo-preview.json',
  JSON.stringify({ count, users, places, toilets, reviews }, null, 2)
);
await writeFile('tmp/cityhall-demo-import.sql', buildSql({ users, places, toilets, reviews }));
await writeFile('tmp/cityhall-demo-cleanup.sql', buildCleanupSql());

console.log(`시청역 근처 데모 데이터 SQL 생성 완료`);
console.log(`- 화장실: ${toilets.length}개`);
console.log(`- 리뷰: ${reviews.length}개`);
console.log(`- import: tmp/cityhall-demo-import.sql`);
console.log(`- cleanup: tmp/cityhall-demo-cleanup.sql`);

function buildSql({ users, places, toilets, reviews }) {
  return [
    '-- Generated by scripts/generateCityHallDemoToilets.mjs',
    '-- Temporary demo data around City Hall Station. Delete later with tmp/cityhall-demo-cleanup.sql.',
    'begin;',
    buildInsertSql('users', ['id', 'nickname'], users),
    buildInsertSql('places', ['id', 'name', 'address', 'lat', 'lng', 'source', 'kakao_place_id'], places),
    buildInsertSql(
      'toilets',
      ['id', 'place_id', 'type', 'access_type', 'floor', 'gender_type', 'registered_by'],
      toilets
    ),
    reviews.length > 0
      ? buildInsertSql(
          'reviews',
          [
            'id',
            'toilet_id',
            'user_id',
            'rating',
            'cleanliness',
            'paper',
            'soap',
            'security',
            'comment',
            'is_verified',
          ],
          reviews
        )
      : '',
    'commit;',
    '',
  ].join('\n\n');
}

function buildCleanupSql() {
  return [
    '-- Delete temporary City Hall demo data.',
    'begin;',
    `delete from reviews where toilet_id in (
  select t.id
  from toilets t
  join places p on p.id = t.place_id
  where p.kakao_place_id like '${prefix}:%'
);`,
    `delete from toilets where place_id in (
  select id from places where kakao_place_id like '${prefix}:%'
);`,
    `delete from places where kakao_place_id like '${prefix}:%';`,
    `delete from users where id = '${users[0].id}';`,
    'commit;',
    '',
  ].join('\n\n');
}

function buildInsertSql(table, columns, rows) {
  if (rows.length === 0) return '';

  const values = rows
    .map((row) => `  (${columns.map((column) => sqlValue(row[column])).join(', ')})`)
    .join(',\n');

  const updates = columns
    .filter((column) => column !== 'id')
    .map((column) => `${column} = excluded.${column}`)
    .join(', ');

  return [
    `insert into ${table} (${columns.join(', ')}) values`,
    values,
    `on conflict (id) do update set ${updates};`,
  ].join('\n');
}

function randomPoint(lat, lng, radiusKm) {
  const distance = radiusKm * Math.sqrt(random());
  const angle = random() * Math.PI * 2;
  const deltaLat = (distance * Math.cos(angle)) / 111;
  const deltaLng = (distance * Math.sin(angle)) / (111 * Math.cos((lat * Math.PI) / 180));
  return { lat: lat + deltaLat, lng: lng + deltaLng };
}

function sample(items) {
  return items[Math.floor(random() * items.length)];
}

function seededRandom(initialSeed) {
  let state = initialSeed >>> 0;
  return () => {
    state = (1664525 * state + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

function stableUuid(input) {
  const hex = createHash('sha1').update(input).digest('hex').slice(0, 32);
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-5${hex.slice(13, 16)}-a${hex.slice(17, 20)}-${hex.slice(20, 32)}`;
}

function round(value, digits) {
  const multiplier = 10 ** digits;
  return Math.round(value * multiplier) / multiplier;
}

function sqlValue(value) {
  if (value == null || value === '') return 'null';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function parseArgs(argv) {
  return argv.reduce((acc, item) => {
    if (!item.startsWith('--')) return acc;
    const [key, ...rest] = item.slice(2).split('=');
    acc[key] = rest.join('=') || 'true';
    return acc;
  }, {});
}
